### PR TITLE
Initial setup of my Industrial Edge App

### PR DESCRIPTION
**Pull request by Chris1612**
Intial commit of first Industrial Edge Application of the Siemens Industrial Edge Developer Guide

### CODE REVIEW

**Comment by EndyCZ** [comment]
Missing license and readme file description.

**Comment by EndyCZ** [comment]
Can you make the background of your image white please? instead of transparent? 
image

**Comment by Chris1612** [comment]
Sure i will update the image with a white background

**Comment by Chris1612** [comment]
@EndyCZ It is fixed

**Comment by EndyCZ** [comment]
I have tested the first part of the application in local dev enviroment. Here are my comments so far. 

Readme notes
- The readme file does not follow the markdown linter practices 
    - Use Markdown Linter, There can be NO WARNINGs https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint 
- Missing prerequisites section in readme 
    - For example I would add where to find app developer guide (at least that it will be published to SIOS)
- Link to docs does not work
- It is not SIMATIC Flow Creator but IE Flow Creator - they changed it :/

Flow Creator

- Change the name of dir. It is called IE Flow Creator and Simatic flow creator
- Change the naming accordingly in the readme file

My-edge-app
- Docker-compose.yml- Would it make sense to mark the proxy-redirect **not** as external?
- docker-compose_Edge.yml - Network - why driver: bridge? it is the default
 

The pull request can be accepted when we publish the application developer guide in SIOS or wherever so that the documentation is complete.

**Comment by EndyCZ** [comment]
Please add note for external network in docker-compose.yml files saying that it needs to be created manualy.

**Review by EndyCZ — APPROVED** [review]
The overall application example is ready for release.

**Pull request merged**
